name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test_functional:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/functional
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test

  test_imperative:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/imperative
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pytest==8.1.1 black==24.4.0
      - run: python -m pytest .
      - run: black --check src test
